/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as StatsRouteImport } from './../pages/stats'
import { Route as AuthRouteImport } from './../pages/auth'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as ChatsChatIdRouteImport } from './../pages/chats.$chatId'
import { Route as ChatsChatIdPrintRouteImport } from './../pages/chats.$chatId_.print'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsChatIdRoute = ChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsChatIdPrintRoute = ChatsChatIdPrintRouteImport.update({
  id: '/chats/$chatId_/print',
  path: '/chats/$chatId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/stats': typeof StatsRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/$chatId/print': typeof ChatsChatIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/stats': typeof StatsRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/$chatId/print': typeof ChatsChatIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/stats': typeof StatsRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/$chatId_/print': typeof ChatsChatIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/stats'
    | '/chats/$chatId'
    | '/chats/$chatId/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/stats' | '/chats/$chatId' | '/chats/$chatId/print'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/stats'
    | '/chats/$chatId'
    | '/chats/$chatId_/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StatsRoute: typeof StatsRoute
  ChatsChatIdRoute: typeof ChatsChatIdRoute
  ChatsChatIdPrintRoute: typeof ChatsChatIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$chatId': {
      id: '/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof ChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$chatId_/print': {
      id: '/chats/$chatId_/print'
      path: '/chats/$chatId/print'
      fullPath: '/chats/$chatId/print'
      preLoaderRoute: typeof ChatsChatIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StatsRoute: StatsRoute,
  ChatsChatIdRoute: ChatsChatIdRoute,
  ChatsChatIdPrintRoute: ChatsChatIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
