apiVersion: 1
datasources:
  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    database: "logstash-*"
    jsonData:
      esVersion: "8.5.3"
      timeField: "@timestamp"
      logMessageField: msg
      logLevelField: level
      maxConcurrentShardRequests: 5
