"""add_chats_messages

Revision ID: d109aea730ae
Revises: d52ef149711a
Create Date: 2026-04-18 15:40:55.211913

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d109aea730ae"
down_revision: str | Sequence[str] | None = "d52ef149711a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
